### ISSUE TITLE
Problem Placebo

### ISSUE THREAD

**Issue by remoda** [ThomasDavid0/Placebo_F3A#1]
I can't download the Placebo  f3a model files model files how can I do thanks Remo

**Comment by ThomasDavid0** [comment]
Hi Remo, the best way is to install git on your computer and clone the repository. There are lots of instructions online about how to do this, for example here: https://www.toolsqa.com/git/git-clone/

**Comment by remoda** [comment]
Thank you so much Thomas can't you send me the dwx files of the Placebo it's a bit difficult for me I'm not very practical thanks again Remo
________________________________
Da: ThomasDavid0 ***@***.***>
Inviato: sabato 11 marzo 2023 14:52
A: ThomasDavid0/Placebo_F3A ***@***.***>
Cc: remoda ***@***.***>; Author ***@***.***>
Oggetto: Re: [ThomasDavid0/Placebo_F3A] Problem Placebo (Issue #1)


Hi Remo, the best way is to install git on your computer and clone the repository. There are lots of instructions online about how to do this, for example here: https://www.toolsqa.com/git/git-clone/

**Comment by ThomasDavid0** [comment]
I could add some links to the GitHub pages site(https://thomasdavid0.github.io/Placebo_F3A/) so that you can download them from there. If I get a chance I'll do that when I get to work next week.

**Comment by remoda** [comment]
Thomas sorry for the inconvenience can you send me the dxf files of the model what you sent me are the building instructions thank you very much bye Remo
________________________________
Da: ThomasDavid0 ***@***.***>
Inviato: sabato 11 marzo 2023 18:38
A: ThomasDavid0/Placebo_F3A ***@***.***>
Cc: remoda ***@***.***>; Author ***@***.***>
Oggetto: Re: [ThomasDavid0/Placebo_F3A] Problem Placebo (Issue #1)


I could add some links to the GitHub pages site(https://thomasdavid0.github.io/Placebo_F3A/) so that you can download them from there. If I get a chance I'll do that when I get to work next week.

**Comment by simonclark63** [comment]
I have managed to download all the design files and bring them into Fusion 360 without too much problem. If it would help, this how I did it. Please note some of the files are very large and so some of the steps take a long time. In some cases, my computer seemed to have frozen for many minutes at a time, but if just wait it all works well:
•	Open up Fusion 360 and create a new project called ‘Placebo’  (or whatever else you want to call it). You will need to have the data panel showing to do this – if it is not then click on the data panel icon near the top left of the screen and make sure you are at the home location.
•	Double click on the Placebo project and then create three new folders called “Fuselage”, “Tail” and “Wing”
•	Now open up your browser and click on https://gmail2697595.autodesk360.com/g/shares/SH9285eQTcf875d3c539fe0a6967fd227ad4
•	This opens up a viewer showing the fuselage structure (it may take some time to load)
•	Click the button labelled ‘Open in Fusion 360’ and wait. You may get a message saying that Fusion 360 is not detected, I just ignore this and wait
•	After maybe a minute or so, you will see the Fusion 360 screen but initially it will be blank. 
•	After some more time (in my case about a minute) a dialog box will open for uploading the files. Make sure that the destination folder is correct (i.e. for the fuselage then in the fuselage folder of the Placebo project) and then click OK
•	Now you will have to wait a long time (in my case several minutes) and it looks like your computer has frozen but eventually all the parts and assemblies will be imported and store in you own personal Fusion 360 data area. You will see a number of individual files in the folder corresponding to the various parts and assemblies.
You can now repeat the above for the wing and tail using the following links:
https://gmail2697595.autodesk360.com/g/shares/SH9285eQTcf875d3c539ebdebecb3c94f6e3
https://gmail2697595.autodesk360.com/g/shares/SH9285eQTcf875d3c5392422d2a3114362d1

Note that these links are also shown on the front page of the Placebo GitHub area:
https://github.com/ThomasDavid0/Placebo_F3A

I hope this helps.
Simon

**Comment by ThomasDavid0** [comment]
I've update the github pages site.
