### ISSUE TITLE
Tail position

### ISSUE THREAD

**Issue by simonclark63** [ThomasDavid0/Placebo_F3A#3]
Hi Tom,
On pictures 'finished1 and finished2' it looks like the elevator hinge line is around 20mm in front of the rudder hinge line but on the CAD and other pictures such as 'finished8' it looks like both hinge lines are coincident. Is this just an illusion due to the angle of the camera position or do you have two different versions of tail position?

Thanks
Simon Clark

**Comment by ThomasDavid0** [comment]
Hi Simon, 

They are pretty much in line. I think its just looks deceiving due to the angle those two pictures are taken from.

cheers,

Tom
