### ISSUE TITLE
Balsa type

### ISSUE THREAD

**Issue by Julien-A81** [ThomasDavid0/Placebo_F3A#4]
Hi Thomas,

Would you please confirm Balsa light is for feather grade?
Have you tried normal grade?

BR
Julien

**Comment by ThomasDavid0** [comment]
Hi Julien,

I built mine with light from a UK supplier about 30 to 35g for 48"X4"x3/32" sheet. The plane came out around 4500g so you could use a bit heavier than that. Try to keep the tail light though for CG.

Cheers,

Tom
