### ISSUE TITLE
Engine recomendation

### ISSUE THREAD

**Issue by edugit** [ThomasDavid0/Placebo_F3A#5]
Hi, 
I would appreciate a recommendation for an affordable engine that fits well with the fuselage and firewall shape. 
Thks

**Comment by ThomasDavid0** [comment]
Hi,

It's designed around the adverrun xs, I haven't tried any other motors in it. Note if you are going single drive you'll need to add some side thrust.

Cheers,

Tom

**Comment by edugit** [comment]
Thank you Thomas for your quick answer,
At this moment Roland Poidevin is cutting me a short kit and I plan to
start building it this winter.

Since it is going to be my first full size F3A  I am trying to be
conservative with all the electronics to install in it. Something balanced
being good enought but not breaking the bank ( at least not to much...)
Whats your opinion of the Dualsky CRS3000? it is almost half the price of
the Adverrun AVR XS, but I am not sure if it is also half the quality....
I am intrigued in how you managed to make the pull pull arragement of the
elevators, I could not find any picture of it yet.

Agan, thank you for your time and your generosity sharing your designs.

Best,
Edu

**Comment by edugit** [comment]
Thank you Thomas for your quick answer,
At this moment I am having  short kit being cut and I plan to start
building it this winter.

Since it is going to be my first full size F3A  I am trying to be
conservative with all the electronics to install in it. Something balanced
being good enought but not breaking the bank ( at least not to much...)
Whats your opinion of the Dualsky CRS3000? it is almost half the price of
the Adverrun AVR XS, but I am not sure if it is also half the quality....
I am intrigued in how you managed to make the pull pull arragement of the
elevators, I could not find any picture of it yet.

Again, thank you for your time and your generosity sharing your designs.

Best,
